language: ruby
cache: bundler
rvm:
  - 2.2.4
services:
  - postgresql
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -c 'create database SDcan5_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
